name: iDisguiseWG
main: de.robingrether.idisguise.worldguard.iDisguiseWG
version: ${project.version}
author: Robin Grether
depend: [iDisguise, WorldGuard]
website: https://dev.bukkit.org/projects/idisguise-wg
load: STARTUP