name: iDisguiseWG
main: de.robingrether.idisguise.worldguard.iDisguiseWG
version: ${project.version}
api-version: 1.13
author: Robin Grether
depend: [iDisguise, WorldGuard]
website: https://www.spigotmc.org/resources/idisguisewg.31156/